function createfigure(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 11-Apr-2018 16:16:51

% Create figure
figure1 = figure('NumberTitle','off','Name','2impulse response for capital');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(Y1);

box(axes1,'on');
